' ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
'< _tobac.bas modul generated by utility                     GladeToBac V3.4.1 >
'< Modul _tobac.bas erzeugt von                                                >
'< Generated at / Generierung am                             2015-01-30, 19:23 >
' -----------------------------------------------------------------------------
'< Main/Haupt Program name: fbdbg.bas                                          >
'< Author:  SARG, AGS, TJF                                                     >
'<  Email:  Thomas.Freiherr@gmx.net                                            >
'<    WWW:  github.com/fbdbg                                                   >
' -----------------------------------------------------------------------------
'< declare names, signal handlers, load GUI-XML                   do not edit! >
'< deklariert Namen, Signale, laedt GUI-XML                  nicht veraendern! >
' vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

SCOPE
  VAR er = gtk_check_version(3, 6, 0)
  IF er THEN
    ?"Fehler/Error (GTK-Version):"
    ?*er
    END 1
  END IF
END SCOPE

TYPE GUIData
  AS GtkBuilder PTR XML
  AS GObject PTR _
  window1, lstoreMemory, srcbuff, srcbuffCur, tstoreProcVar, tstoreProcs,  _
  tstoreThreads, tstoreWatch, sbarlab1, sbarlab2, sbarlab3, sbarlab4, sbarlab5,  _
  srcviewCur, nbookSrc, srcview, nbook2, tviewProcVar, tviewProcs, tviewThreads,  _
  tviewWatch, lviewMemory, comboBookmarks, watch1, watch3, watch2, watch4
END TYPE
DIM SHARED AS GUIData GUI

GUI.XML = gtk_builder_new()

SCOPE
DIM AS GError PTR meld
IF 0 = gtk_builder_add_from_file(GUI.XML, "fbdbg.ui", @meld) THEN
  WITH *meld
    ?"Fehler/Error (GTK-Builder):"
    ?*.message
  END WITH
  g_error_free(meld)
  END 2
END IF
END SCOPE

WITH GUI
  .window1 = gtk_builder_get_object(.XML, "window1")
  .lstoreMemory = gtk_builder_get_object(.XML, "lstoreMemory")
  .srcbuff = gtk_builder_get_object(.XML, "srcbuff")
  .srcbuffCur = gtk_builder_get_object(.XML, "srcbuffCur")
  .tstoreProcVar = gtk_builder_get_object(.XML, "tstoreProcVar")
  .tstoreProcs = gtk_builder_get_object(.XML, "tstoreProcs")
  .tstoreThreads = gtk_builder_get_object(.XML, "tstoreThreads")
  .tstoreWatch = gtk_builder_get_object(.XML, "tstoreWatch")
  .sbarlab1 = gtk_builder_get_object(.XML, "sbarlab1")
  .sbarlab2 = gtk_builder_get_object(.XML, "sbarlab2")
  .sbarlab3 = gtk_builder_get_object(.XML, "sbarlab3")
  .sbarlab4 = gtk_builder_get_object(.XML, "sbarlab4")
  .sbarlab5 = gtk_builder_get_object(.XML, "sbarlab5")
  .srcviewCur = gtk_builder_get_object(.XML, "srcviewCur")
  .nbookSrc = gtk_builder_get_object(.XML, "nbookSrc")
  .srcview = gtk_builder_get_object(.XML, "srcview")
  .nbook2 = gtk_builder_get_object(.XML, "nbook2")
  .tviewProcVar = gtk_builder_get_object(.XML, "tviewProcVar")
  .tviewProcs = gtk_builder_get_object(.XML, "tviewProcs")
  .tviewThreads = gtk_builder_get_object(.XML, "tviewThreads")
  .tviewWatch = gtk_builder_get_object(.XML, "tviewWatch")
  .lviewMemory = gtk_builder_get_object(.XML, "lviewMemory")
  .comboBookmarks = gtk_builder_get_object(.XML, "comboBookmarks")
  .watch1 = gtk_builder_get_object(.XML, "watch1")
  .watch3 = gtk_builder_get_object(.XML, "watch3")
  .watch2 = gtk_builder_get_object(.XML, "watch2")
  .watch4 = gtk_builder_get_object(.XML, "watch4")
END WITH

#INCLUDE "act_runto.bas"
#INCLUDE "act_step.bas"
#INCLUDE "act_step_over.bas"
#INCLUDE "act_step_out.bas"
#INCLUDE "act_step_start.bas"
#INCLUDE "act_step_end.bas"
#INCLUDE "act_run.bas"
#INCLUDE "act_fastrun.bas"
#INCLUDE "act_stop.bas"
#INCLUDE "act_kill.bas"
#INCLUDE "act_auto.bas"
#INCLUDE "act_ToDo.bas"
#INCLUDE "act_exemod.bas"
#INCLUDE "act_Shortcut.bas"
#INCLUDE "act_free.bas"
#INCLUDE "act_minicmd.bas"
#INCLUDE "act_restart.bas"
#INCLUDE "act_multiexe.bas"
#INCLUDE "act_attachexe.bas"
#INCLUDE "act_files.bas"
#INCLUDE "act_tools.bas"
#INCLUDE "act_notes.bas"
#INCLUDE "act_source.bas"
#INCLUDE "act_varproc.bas"
#INCLUDE "act_memory.bas"
#INCLUDE "act_Settings.bas"
#INCLUDE "act_help.bas"
#INCLUDE "on_entry_icon_load.bas"
#INCLUDE "on_entry_icon_save.bas"
#INCLUDE "on_accel_cleared.bas"
#INCLUDE "on_accel_edited.bas"
#INCLUDE "menu_button3_event.bas"
#INCLUDE "on_boolcell_toggled.bas"
#INCLUDE "on_StopVar_clicked.bas"
#INCLUDE "on_comboBookmarks_changed.bas"

