' ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
'< Signal handler generated by utility                         GladeToBac V3.4 >
'< Signal-Modul erzeugt von                                                    >
'< Generated at / Generierung am                             2015-01-21, 14:21 >
' -----------------------------------------------------------------------------
'< Main/Haupt Program name: main.bas                                           >
'< Author:  SARG, AGS, TJF                                                     >
'<  Email:  Thomas.Freiherr@gmx.net                                            >
' -----------------------------------------------------------------------------
'< callback SUB/FUNCTION                                          insert code! >
'< Ereignis Unterprogramm/Funktion                        Quelltext einfuegen! >
' vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
FUNCTION menu_button3_event CDECL ALIAS "menu_button3_event" ( _
  BYVAL widget AS GtkWidget PTR, _
  BYVAL event AS GdkEvent PTR, _
  BYVAL user_data AS gpointer) AS gboolean EXPORT ' Standard-Parameterliste

  WITH *cast(GdkEventButton PTR, event)
    IF .button <> 3 THEN RETURN FALSE
    gtk_menu_popup(user_data, NULL, NULL, NULL, NULL, .button, .time)
  END WITH
  RETURN TRUE

END FUNCTION
