' ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
'< Signal handler generated by utility                       GladeToBac V3.4.1 >
'< Signal-Modul erzeugt von                                                    >
'< Generated at / Generierung am                             2015-01-27, 23:35 >
' -----------------------------------------------------------------------------
'< Main/Haupt Program name: fbdbg.bas                                          >
'< Author:  SARG, AGS, TJF                                                     >
'<  Email:  Thomas.Freiherr@gmx.net                                            >
' -----------------------------------------------------------------------------
'< callback SUB/FUNCTION                                          insert code! >
'< Ereignis Unterprogramm/Funktion                        Quelltext einfuegen! >
' vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
SUB on_accel_cleared CDECL ALIAS "on_accel_cleared" ( _
  BYVAL accel AS GtkCellRendererAccel PTR, _
  BYVAL path_string AS gchar PTR, _
  BYVAL user_data AS gpointer) EXPORT

' place your source code here / eigenen Quelltext hier einfuegen
?*__("--> callback on_accel_cleared")

END SUB
