' ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
'< Signal handler generated by utility                       GladeToBac V3.4.1 >
'< Signal-Modul erzeugt von                                                    >
'< Generated at / Generierung am                             2015-01-27, 23:35 >
' -----------------------------------------------------------------------------
'< Main/Haupt Program name: fbdbg.bas                                          >
'< Author:  SARG, AGS, TJF                                                     >
'<  Email:  Thomas.Freiherr@gmx.net                                            >
' -----------------------------------------------------------------------------
'< callback SUB/FUNCTION                                          insert code! >
'< Ereignis Unterprogramm/Funktion                        Quelltext einfuegen! >
' vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
SUB on_accel_edited CDECL ALIAS "on_accel_edited" ( _
  BYVAL accel AS GtkCellRendererAccel PTR, _
  BYVAL path_string AS gchar PTR, _
  BYVAL accel_key AS guint, _
  BYVAL accel_mods AS GdkModifierType, _
  BYVAL hardware_keycode AS guint, _
  BYVAL user_data AS gpointer) EXPORT

' place your source code here / eigenen Quelltext hier einfuegen
?*__("--> callback on_accel_edited")
  DIM AS GtkTreeIter iter
  VAR model = GTK_TREE_MODEL(user_data)
  gtk_tree_model_get_iter_from_string(model, @iter, path_string)
  gtk_list_store_set(user_data, @iter _
    , 0, accel_key _
    , 1, accel_mods _
    , -1) '                                  parameter list terminator

END SUB
