' ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
'< Signal handler generated by utility                       GladeToBac V3.4.1 >
'< Signal-Modul erzeugt von                                                    >
'< Generated at / Generierung am                             2015-01-27, 16:56 >
' -----------------------------------------------------------------------------
'< Main/Haupt Program name: main.bas                                           >
'< Author:  SARG, AGS, TJF                                                     >
'<  Email:  Thomas.Freiherr@gmx.net                                            >
' -----------------------------------------------------------------------------
'< callback SUB/FUNCTION                                          insert code! >
'< Ereignis Unterprogramm/Funktion                        Quelltext einfuegen! >
' vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
SUB on_boolcell_toggled CDECL ALIAS "on_boolcell_toggled" ( _
  BYVAL cell_renderer AS GtkCellRendererToggle PTR, _
  BYVAL path AS gchar PTR, _
  BYVAL user_data AS gpointer) EXPORT

  DIM AS gboolean v
  DIM AS GtkTreeIter iter
  VAR model = GTK_TREE_MODEL(user_data)
  gtk_tree_model_get_iter_from_string(model, @iter, path)
  gtk_tree_model_get(model, @iter, 1, @v, -1)
  gtk_tree_store_set(user_data, @iter, 1, IIF(v, 0, 1), -1)

END SUB
