' ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
'< main program generated by utility                           GladeToBac V3.4 >
'< Hauptprogramm erzeugt von                                                   >
'< Generated at / Generierung am                             2015-01-20, 10:56 >
' -----------------------------------------------------------------------------
'< Program info:                                                               >
CONST PROJ_NAME = "fbdbg" '                                                    >
CONST PROJ_DESC = "Debugger for FreeBASIC" '                                   >
CONST PROJ_VERS = "3.0" '                                                      >
CONST PROJ_YEAR = "2015" '                                                     >
CONST PROJ_AUTH = "SARG, AGS, TJF" '                                           >
CONST PROJ_MAIL = "Thomas.Freiherr@gmx.net" '                                  >
CONST PROJ_WEBS = "" '                                                         >
CONST PROJ_LICE = "GPLv3" '                                                    >
'<                                                                             >
'< Description / Beschreibung:                                                 >
'<                                                                             >
'<                                                                             >
'< License / Lizenz:                                                           >
'<                                                                             >
'< Put your license here/Lizenz hier einfuegen.
'<                                                                             >
' -----------------------------------------------------------------------------
'<  GladeToBac:                    general init / Allgemeine Initialisierungen >
    #INCLUDE "Gir/Gtk-3.0.bi" '                  GTK+library / GTK+ Bibliothek >
    #INCLUDE "Gir/GtkSource-3.0.bi" '            GTK+library / GTK+ Bibliothek >
    gtk_init(@__FB_ARGC__, @__FB_ARGV__) '             start GKT / GTK starten >
    #INCLUDE "libintl.bi" '                               load lib / Lib laden >
    bindtextdomain(PROJ_NAME, EXEPATH & "/locale") '               path / Pfad >
    bind_textdomain_codeset(PROJ_NAME, "UTF-8") '   set encoding / Zeichensatz >
    textdomain(PROJ_NAME) '                               Filename / Dateiname >
'<  GladeToBac:                                          end block / Blockende >
' vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv



' ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
'<  GladeToBac:                                 load GTK stuff / GTK Anbindung >
    #INCLUDE "tobac/main_tobac.bas" '                        Signale & GUI-XML >
'<  GladeToBac:                                          end block / Blockende >
' vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

#INCLUDE ONCE "testing.bas"

' ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
'<  GladeToBac:          run GTK main, then end / GTK Hauptschleife, dann Ende >
    gtk_builder_connect_signals(GUI_MAIN.XML, 0) '            Signale anbinden >
    gtk_main() '                                     main loop / Hauptschleife >
    g_object_unref(GUI_MAIN.XML) '              dereference / Referenz abbauen >
'<  GladeToBac:                                          end block / Blockende >
' vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
